name: Build and Unit test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name : Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: NPM Install
      run: npm install
    - name: Run unit tests
      run: npm run test:unit
    - name: Display my username
      run: echo "tanatis"

  run_unit_tests:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
    - name : Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: NPM Install
      run: npm install
    - name: Install playwright
      run: npx playwright install
    - name: Start App
      run: npm run start &
    - name: Run UI tests
      run: npm run test:ui
